'use client';

import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Button } from '@/components/ui/button';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { db } from '@/lib/firebase/firebase';
import { collection, addDoc } from 'firebase/firestore';
import { Deal, DealStage } from '@/lib/types';

const dealStageValues = [
  "Qualified",
  "Solutioning",
  "Proposal Sent",
  "Negotiation",
  "LoI Initiated",
  "LoI Signed",
  "Lost",
] as const;

const formSchema = z.object({
  deal_code: z.string().min(1, 'Deal code is required'),
  company_name: z.string().min(1, 'Company name is required'),
  stage: z.enum(dealStageValues),
});

export const NewDealForm = () => {
  const router = useRouter();
  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      deal_code: '',
      company_name: '',
      stage: "Qualified",
    },
  });

  const onSubmit = async (values: z.infer<typeof formSchema>) => {
    try {
      const docRef = await addDoc(collection(db, 'deals'), {
        ...values,
        deal_id: '', // This will be auto-generated by Firestore
        sales_owner_email: '', // Or get from logged in user
        building_id: '',
        layout_status: 'not_requested',
        layout_revision_count: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      console.log('Document written with ID: ', docRef.id);
      router.push('/deals');
    } catch (error) {
      console.error('Error adding document: ', error);
    }
  };

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
        <FormField
          control={form.control}
          name="deal_code"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Deal Code</FormLabel>
              <FormControl>
                <Input placeholder="Enter deal code" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="company_name"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Company Name</FormLabel>
              <FormControl>
                <Input placeholder="Enter company name" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="stage"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Stage</FormLabel>
              <Select onValueChange={field.onChange} defaultValue={field.value}>
                <FormControl>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a stage" />
                  </SelectTrigger>
                </FormControl>
                <SelectContent>
                  {dealStageValues.map((stage) => (
                    <SelectItem key={stage} value={stage}>
                      {stage}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <FormMessage />
            </FormItem>
          )}
        />
        <Button type="submit">Create Deal</Button>
      </form>
    </Form>
  );
};
